repos:
  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v6.0.0
  #   hooks:
  #     - id: check-added-large-files
  #     - id: check-ast
  #     - id: check-case-conflict
  #     - id: check-json
  #     - id: check-merge-conflict
  #     - id: check-symlinks
  #     - id: check-xml
  #     - id: check-yaml
  #     - id: end-of-file-fixer
  #     - id: no-commit-to-branch
  #     - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.13
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        args: [--strict, --ignore-missing-imports]
        additional_dependencies: [lume-model, trame, trame-vuetify]
